services:
  postgres:
    container_name: amigos_postgres
    image: postgres
    environment:
      POSTGRES_USER: amigos
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres_net
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

networks:
  postgres_net:
    driver: bridge

volumes:
  postgres: